const RIGHTS = [
  "ADD_USERS", "VIEW_USERS", "DELETE_USERS",
  "ADD_COMPANIES", "VIEW_COMPANIES", "DELETE_COMPANIES", "DELETE_JOB_POSITION", "CREATE_BANK_DETAILS", "VIEW_BANK_DETAILS", "CREATE_APPLICANT", "DELETE_APPLICANT",
  "VIEW_APPLICANT_PROFILE", "VIEW_APPLICANT_INFORMATION", "UPLOAD_DOCUMENT", "VIEW_DOCUMENTS", "ADD_DOCUMENT_DISPATCH", "VIEW_DOCUMENT_DISPATCH",
  "ISSUE_CONTRACT", "UPLOAD_SIGNED_CONTRACT", "VIEW_SIGNED_CONTRACT", "INITIATE_EMBASSY_APPOINTMENT",
  "VIEW_EMBASSY_APPOINTMENT", "ADD_APPOINTMENT_TRAVEL", "ADD_APPOINTMENT_BIOMETRIC", "VIEW_APPOINTMENT_TRAVEL_BIOMETRIC",
  "INITIATE_EMBASSY_INTERVIEW", "VIEW_EMBASSY_INTERVIEW", "ADD_INTERVIEW_TRAVEL", "ADD_INTERVIEW_BIOMETRIC",
  "VIEW_INTERVIEW_TRAVEL_BIOMETRIC", "INITIATE_VISA_COLLECTION", "VIEW_VISA_COLLECTION", "ADD_VISA_TRAVEL",
  "VIEW_VISA_TRAVEL", "UPLOAD_TRC", "VIEW_TRC", "ADD_APPLICANT_ARRIVAL", "VIEW_APPLICANT_ARRIVAL",
  "COMPLETE_APPLICANT_ARRIVAL", "ADD_PAYMENT_DETAILS", "VIEW_PAYMENT_DETAILS", "ACKNOWLEDGE_PAYMENT", "CONFIRM_PAYMENT"
];

const ROLE_DEFAULT_RIGHTS = {
  SUPER_USER: RIGHTS,
  ADMIN: RIGHTS.filter((right) => !["DELETE_USERS", "DELETE_COMPANIES", "DELETE_JOB_POSITION", "DELETE_APPLICANT"].includes(right)),
  EMPLOYER: [
    "VIEW_APPLICANT_PROFILE", "VIEW_APPLICANT_INFORMATION", "VIEW_DOCUMENTS", "VIEW_DOCUMENT_DISPATCH", "ISSUE_CONTRACT", "VIEW_SIGNED_CONTRACT",
    "INITIATE_EMBASSY_APPOINTMENT", "VIEW_EMBASSY_APPOINTMENT", "VIEW_APPOINTMENT_TRAVEL_BIOMETRIC",
    "INITIATE_EMBASSY_INTERVIEW", "VIEW_EMBASSY_INTERVIEW", "VIEW_INTERVIEW_TRAVEL_BIOMETRIC",
    "INITIATE_VISA_COLLECTION", "VIEW_VISA_COLLECTION", "VIEW_VISA_TRAVEL", "VIEW_TRC", "VIEW_APPLICANT_ARRIVAL"
  ],
  AGENCY: [
    "CREATE_APPLICANT", "VIEW_APPLICANT_PROFILE", "VIEW_APPLICANT_INFORMATION", "UPLOAD_DOCUMENT", "VIEW_DOCUMENTS", "ADD_DOCUMENT_DISPATCH",
    "VIEW_DOCUMENT_DISPATCH", "UPLOAD_SIGNED_CONTRACT", "VIEW_SIGNED_CONTRACT", "VIEW_EMBASSY_APPOINTMENT",
    "ADD_APPOINTMENT_TRAVEL", "ADD_APPOINTMENT_BIOMETRIC", "VIEW_APPOINTMENT_TRAVEL_BIOMETRIC", "VIEW_EMBASSY_INTERVIEW",
    "ADD_INTERVIEW_TRAVEL", "ADD_INTERVIEW_BIOMETRIC", "VIEW_INTERVIEW_TRAVEL_BIOMETRIC", "VIEW_VISA_COLLECTION",
    "ADD_VISA_TRAVEL", "VIEW_VISA_TRAVEL", "UPLOAD_TRC", "VIEW_TRC", "ADD_APPLICANT_ARRIVAL", "VIEW_APPLICANT_ARRIVAL",
    "ADD_PAYMENT_DETAILS", "VIEW_PAYMENT_DETAILS"
  ],
  JUNIOR_ACCOUNTANT: ["ACKNOWLEDGE_PAYMENT", "VIEW_PAYMENT_DETAILS"],
  SENIOR_ACCOUNTANT: ["VIEW_APPLICANT_PROFILE", "VIEW_APPLICANT_INFORMATION", "VIEW_PAYMENT_DETAILS", "CONFIRM_PAYMENT"]
};

function normalizeRole(role) {
  const value = String(role || "").trim().toUpperCase();
  if (value === "AGENT") return "AGENCY";
  return value;
}

function getDefaultRights(role) {
  return [...(ROLE_DEFAULT_RIGHTS[normalizeRole(role)] || [])];
}

function getEffectiveRights(user = {}) {
  // Explicit rights add to, rather than replace, the legacy capabilities of a
  // user's role. A feature is available when either source grants its right.
  const explicitRights = Array.isArray(user.rights) ? user.rights.filter((right) => RIGHTS.includes(right)) : [];
  return [...new Set([...getDefaultRights(user.role), ...explicitRights])];
}

function hasRight(user, right) {
  return getEffectiveRights(user).includes(right);
}

module.exports = { RIGHTS, ROLE_DEFAULT_RIGHTS, getDefaultRights, getEffectiveRights, hasRight, normalizeRole };
